name: App Image CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master


jobs:
  build_app_image:
    name: Build app image
    runs-on: ubuntu-latest
    env:
      DH_REGISTRY: docker.io
      GH_REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      REPOSITORY: ${{ github.event.repository.name }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: ${{ env.GITHUB_SERVER_URL == 'https://github.com' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Define metadata variables
        run: |
          sed -i "s/ARG githash=.*/ARG githash=${{ github.sha }}/" Dockerfile
          sed -i "s/ARG created=.*/ARG created=$(date -u +'%Y-%m-%dT%H:%M:%S%:z')/" Dockerfile
          cat Dockerfile
      
      - name: Define metadata variables
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sed -i "s/ARG version=.*/ARG version=${{ github.ref_name }}/" Dockerfile
          cat Dockerfile
      
      - name: Extract metadata for release Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_USERNAME }}/${{ env.REPOSITORY }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      
      - name: Extract metadata for develop Docker image
        if: "!startsWith(github.ref, 'refs/tags/v')"
        id: meta-develop
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push release Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v6
        with:
          target: deploy
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push develop Docker image
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: docker/build-push-action@v6
        with:
          target: deploy
          push: ${{ env.GITHUB_SERVER_URL == 'https://github.com' }}
          tags: ${{ steps.meta-develop.outputs.tags }}
          labels: ${{ steps.meta-develop.outputs.labels }}
          platforms: linux/amd64,linux/arm64
